blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/your-org/your-repo/wiki
    about: Check the documentation for help and guides
  - name: Discussions
    url: https://github.com/your-org/your-repo/discussions
    about: Ask questions and discuss ideas with the community
