logging:
  level:
    ROOT: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onu
    username: ENC(YZTGGG87DZAknKifLcI1SA==)
    password:


application:
  profile:
    name: seonwoo
    email: seonwoo960000@naver.com
  credential:
    password: hello_password_world
jasypt:
  encryptor:
    password: hello
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator