### GET address
GET http://localhost:8080/address/1

### Get category
GET http://localhost:8080/category/Action

### Save payment
POST http://localhost:8080/payment
Content-Type: application/json

{
  "id": null,
  "customerId": 1,
  "staffId": 1,
  "rentalId": null,
  "amount": 5.00,
  "paymentDate": "2022-05-28T10:35:23Z",
  "lastUpdate": "2022-05-28T10:35:23Z"
}