logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG
      data.r2dbc: DEBUG

#management:
#  endpoints:
#    web:
#      exposure:
#        include: httptrace

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
  r2dbc:
    name: onu
    url: r2dbc:mysql://localhost:3306/onu?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    pool:
      max-size: 50
  jackson.serialization.indent_output: true


application:
  name: template