logging:
  level:
    ROOT: INFO
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      read-only: false
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      # don't use ALWAYS. create batch meta tables manually with schema-mysql.sql
      initialize-schema: NEVER